version: "2"
sql:
  - schema: "../sql/schema"
    queries: "../sql/queries"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "../internal/db"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_pointers_for_null_types: true
#        emit_methods_with_db_argument: true
