// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Branch struct {
	ID             int64        `json:"id"`
	Name           string       `json:"name"`
	Location       pgtype.Point `json:"location"`
	OrganizationID int64        `json:"organization_id"`
}

type Order struct {
	ID           int64            `json:"id"`
	CustomerName string           `json:"customer_name"`
	City         *string          `json:"city"`
	Street       *string          `json:"street"`
	Apartment    *string          `json:"apartment"`
	Floor        *int32           `json:"floor"`
	Entrance     *int32           `json:"entrance"`
	Comment      *string          `json:"comment"`
	Cost         pgtype.Numeric   `json:"cost"`
	Status       *string          `json:"status"`
	Location     pgtype.Point     `json:"location"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Organization struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Balance      pgtype.Numeric `json:"balance"`
	IikoApiToken string         `json:"iiko_api_token"`
}

type OrganizationPlan struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	PlanID         int64       `json:"plan_id"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
}

type Payment struct {
	ID             int64            `json:"id"`
	OrganizationID int64            `json:"organization_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	PaymentDate    pgtype.Timestamp `json:"payment_date"`
	PaymentMethod  string           `json:"payment_method"`
}

type Plan struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Cost          pgtype.Numeric `json:"cost"`
	EmployeeLimit int32          `json:"employee_limit"`
}

type PlanFeature struct {
	ID          int64  `json:"id"`
	PlanID      int64  `json:"plan_id"`
	FeatureName string `json:"feature_name"`
}

type Revision struct {
	RevisionID     int64  `json:"revision_id"`
	OrganizationID *int64 `json:"organization_id"`
}

type Ride struct {
	ID        int64            `json:"id"`
	BranchID  int64            `json:"branch_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	EndedAt   pgtype.Timestamp `json:"ended_at"`
}

type RidesToOrder struct {
	ID      int64 `json:"id"`
	RideID  int64 `json:"ride_id"`
	OrderID int64 `json:"order_id"`
}

type Role struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Session struct {
	ID           int64            `json:"id"`
	UserID       int64            `json:"user_id"`
	SessionToken string           `json:"session_token"`
	RefreshToken string           `json:"refresh_token"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID             int64            `json:"id"`
	Login          string           `json:"login"`
	Password       string           `json:"password"`
	Name           *string          `json:"name"`
	Surname        *string          `json:"surname"`
	Patronymic     *string          `json:"patronymic"`
	OrganizationID int64            `json:"organization_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	ID     int64 `json:"id"`
	RoleID int64 `json:"role_id"`
	UserID int64 `json:"user_id"`
}
