package db

import (
	"context"
	"fmt"
	"smartDriver/internal/config"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *Queries

// InitConnection create new database connection pool and assign it to pointer on Queries
// struct that was generated by SQLC. after call this function you will be able
// to interact with database through Pool global variable.
//
// for example:
//
//	database.Pool.CreateGeolocation(...)
func InitConnection(cfg *config.Config) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, fmt.Sprintf(
		"postgres://%s:%s@%s:%s/%s",
		cfg.Postgres.Username,
		cfg.Postgres.Password,
		cfg.Postgres.Host,
		cfg.Postgres.Port,
		cfg.Postgres.Name,
	))
	if err != nil {
		return err
	}

	Pool = New(pool)
	return nil
}
