package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

var Pool *Queries

// InitConnection create new database connection pool and assign it to pointer on Queries
// struct that was generated by SQLC. after call this function you will be able
// to interact with database through Pool global variable.
//
// for example:
//
//	database.Pool.CreateGeolocation(...)
func InitConnection() error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, "postgres://postgres:1234qwerASDF@localhost:5432/alarm_db")
	if err != nil {
		return err
	}

	Pool = New(pool)
	return nil
}
